name: Azure DevOps Pipelines - Matrix Strategy

trigger: none

stages:
- stage: BuildStage
  jobs:

  - job: Build
    strategy:
      matrix:
        Python35:
          PYTHON_VERSION: '3.5'
        Python36:
          PYTHON_VERSION: '3.6'
        Python37:
          PYTHON_VERSION: '3.7'
      maxParallel: 3
    steps:
    - script: echo $(PYTHON_VERSION)

- stage: Test_STAGE
  jobs:
  - job: Test
    strategy:
      matrix:
        WindowsServer2022:
          imageName: 'windows-2022'
          script: 'dir env:'
        WindowsServer2019:
          imageName: 'windows-2019'
          script: 'dir env:'
        ubuntu-22-04:
          imageName: 'ubuntu-22.04'
          script: 'printenv'
        ubuntu-20-04:
          imageName: 'ubuntu-20.04'
          script: 'printenv'
        macos-12-monterey:
          imageName: 'macOS-12'
          script: 'printenv'
        macos-11-bigsur:
          imageName: 'macOS-11'
          script: 'printenv'
      maxParallel: 6
    pool:
      vmImage: $(imageName)
    steps:
    - script: |
        echo $(imageName)
        dir env:
        $(script)